version: "3"
services:
  web:
    restart: always
    build: .
    container_name: web
    command:  "uwsgi --ini uwsgi.ini"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - web_network

  nginx:
    restart: always
    container_name: nginx
    build: ./nginx
    ports:
      - "80:7000"
    depends_on:
      - web
    networks:
      - web_network
    volumes:
      - ./vue-admin-template/dist:/static

networks:
  web_network:
    driver: bridge


